remote_theme: MicrosoftLearning/Jekyll-Theme
url: "https://violet-bora-lee.github.io/mslearn-ai-studio"
exclude:
  - readme.md
  - .github/
header_pages:
  - index.html
author: Microsoft Learning
twitter_username: mslearning
github_username:  MicrosoftLearning
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
  - jekyll-remote-theme
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true
title: Develop generative AI solutions in Azure
